from .Errors import auth
from .Errors.auth import set_error